In [3]:
import numpy as np

arr = np.random.randint(1, 101, (10, 5))
print("Array:\n", arr)

print("Sum of odd numbers:", np.sum(arr[arr % 2 != 0]))
print("Sum of even numbers:", np.sum(arr[arr % 2 == 0]))
print("Sum of diagonal elements:", np.trace(arr))
print("Transpose:\n", arr.T)

rows = arr[1:6]
print("2nd to 6th rows:\n", rows)

arr[1:6] = arr[1:6] * -1
print("After multiplying rows by -1:\n", arr)

flat_sub = rows.flatten()
print("Flattened sub-matrix:", flat_sub)

print("Sum of all elements:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

flat_sorted = np.sort(arr.flatten())
print("Sorted array:", flat_sorted)


Array:
 [[ 60  23   4  14  21]
 [ 60  47  33  80  56]
 [ 68  70  13  72  81]
 [ 92  21  32   7  76]
 [ 46  51  28 100  87]
 [ 56  88  54  42  71]
 [ 56   8  15  25   7]
 [ 28  86  56  16  77]
 [ 27  73  89  79  57]
 [ 35  11  80  57  62]]
Sum of odd numbers: 1007
Sum of even numbers: 1490
Sum of diagonal elements: 214
Transpose:
 [[ 60  60  68  92  46  56  56  28  27  35]
 [ 23  47  70  21  51  88   8  86  73  11]
 [  4  33  13  32  28  54  15  56  89  80]
 [ 14  80  72   7 100  42  25  16  79  57]
 [ 21  56  81  76  87  71   7  77  57  62]]
2nd to 6th rows:
 [[ 60  47  33  80  56]
 [ 68  70  13  72  81]
 [ 92  21  32   7  76]
 [ 46  51  28 100  87]
 [ 56  88  54  42  71]]
After multiplying rows by -1:
 [[  60   23    4   14   21]
 [ -60  -47  -33  -80  -56]
 [ -68  -70  -13  -72  -81]
 [ -92  -21  -32   -7  -76]
 [ -46  -51  -28 -100  -87]
 [ -56  -88  -54  -42  -71]
 [  56    8   15   25    7]
 [  28   86   56   16   77]
 [  27   73   89   79   57]
 [  35   11   80   57   62]]
Flatte

In [4]:
import time
import numpy as np

# Using Python Lists
size = 100
A = [[1 for j in range(size)] for i in range(size)]
B = [[1 for j in range(size)] for i in range(size)]
result = [[0 for j in range(size)] for i in range(size)]

start = time.time()
for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]
end = time.time()

print("Time using Python lists:", end - start)

# Using NumPy
A_np = np.ones((100, 100))
B_np = np.ones((100, 100))

start = time.time()
C_np = np.dot(A_np, B_np)
end = time.time()

print("Time using NumPy:", end - start)


Time using Python lists: 0.24240803718566895
Time using NumPy: 0.003000497817993164


In [5]:
import numpy as np

class ArrayManager:
    def __init__(self, arr):
        self.arr = arr

    def reverse_rows(self):
        return np.array([row[::-1] for row in self.arr])

    def reverse_order_rows(self):
        return self.arr[::-1]

    def reverse_both(self):
        return self.arr[::-1, ::-1]

    def cut_edges(self):
        return self.arr[1:-1, 1:-1]


arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
obj = ArrayManager(arr)

print("Reverse elements in rows:\n", obj.reverse_rows())
print("Reverse rows:\n", obj.reverse_order_rows())
print("Reverse rows and columns:\n", obj.reverse_both())
print("Cut edges:\n", obj.cut_edges())


Reverse elements in rows:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reverse rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reverse rows and columns:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Cut edges:
 [[5]]


In [7]:
import numpy as np

# (i)
A1 = np.array([[1,2],[2,4]])
B1 = np.array([-4,-8])

det1 = np.linalg.det(A1)

if det1 == 0:
    print("Solution (i): No unique solution (infinite solutions exist)")
else:
    X1 = np.linalg.inv(A1).dot(B1)
    print("Solution (i):", X1)


# (ii)
A2 = np.array([[1,2,3],[2,-3,2],[3,1,-1]])
B2 = np.array([6,14,-2])

det2 = np.linalg.det(A2)

if det2 == 0:
    print("Solution (ii): No unique solution")
else:
    X2 = np.linalg.inv(A2).dot(B2)
    print("Solution (ii):", X2)



Solution (i): No unique solution (infinite solutions exist)
Solution (ii): [ 1. -2.  3.]


In [8]:
import numpy as np

arr = np.zeros((10,10), dtype=int)
arr[0,:] = 1
arr[-1,:] = 1
arr[:,0] = 1
arr[:,-1] = 1

print(arr)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [1]:
def flatten_2d(arr):
    result = []
    for row in arr:
        for val in row:
            result.append(val)
    return result

print(flatten_2d([[1,2,3],[4,5,6]]))


[1, 2, 3, 4, 5, 6]


In [2]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr[:] = arr[::-1]
print(arr)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [3]:
import numpy as np

board = np.zeros((8,8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
import numpy as np

arr = np.arange(27).reshape(3,3,3)
middle = arr[:,1,:]

print(middle)


[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


In [5]:
import numpy as np

A = np.array([1,2,3,4,5])
B = np.array([3,4,5,6,7])

common = np.intersect1d(A, B)
print(common)


[3 4 5]
